######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 15 11:53:06 2015
######################################################################

TEMPLATE = app
TARGET = go
DEPENDPATH += .
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4) {
    QT += widgets
}

DEFINES += QT_V4

# Input
HEADERS += MainWindow.hh TestStyle.hh
SOURCES += main.cc MainWindow.cc TestStyle.cc
