######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 15 11:53:06 2015
######################################################################

TEMPLATE = app
TARGET = go
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets
QMAKE_CLEAN   = $(BIN_DIR)/go
QMAKE_CLEAN  += debug/* release/*
CONFIG       += debug_and_release


# Input
HEADERS += MainWindow.hh
SOURCES += main.cc MainWindow.cc
