######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 15 11:53:06 2015
######################################################################

TEMPLATE = app
TARGET = go
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.hh
SOURCES += main.cc MainWindow.cc
