######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 15 11:53:06 2015
######################################################################

TEMPLATE = lib
TARGET = testlib
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets

#QMAKE_CXX = g++
#QMAKE_CC = g++

# Input
HEADERS += src1.hh src2.hh
SOURCES += src1.cc src2.cc
